<a href="https://colab.research.google.com/github/Lulu03damaris/Tareas_M/blob/main/Tarea10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***TAREA N-10***
*DESCOMPOSICION LU*


- Ejercicio 1

In [ ]:
import numpy as np
def multiply(A, B):
  C = np.dot(A, B)
  return C


In [ ]:
A = np.array([[2, -3], [3, 1]])
B = np.array([[1, 5], [2, 0]])
print("Ejercicio  a")

multiply(A, B)

Ejercicio  a


array([[-4, 10],
       [ 5, 15]])

In [ ]:
A = np.array([[2, -3], [3, 1]])
B = np.array([[1, 5, -4], [-3, 2, 0]])
print("Ejercicio  b")
multiply(A, B)

Ejercicio  b


array([[ 11,   4,  -8],
       [  0,  17, -12]])

In [ ]:
A = np.array([[2, -3, 1], [4, 3, 0], [5, 2, -4]])
B = np.array([[0, 1, -2], [1, 0, -1], [2, 3, -2]])
print("Ejercicio  c")
multiply(A, B)

Ejercicio  c


array([[ -1,   5,  -3],
       [  3,   4, -11],
       [ -6,  -7,  -4]])

In [ ]:
A = np.array([[2, 1, 2], [-2, 3, 0], [2, -1, 3]])
B = np.array([[1, -2], [-4, 1], [0, 2]])
print("Ejercicio  d")
multiply(A, B)

Ejercicio  d


array([[ -2,   1],
       [-14,   7],
       [  6,   1]])

- Ejercicio 2

In [ ]:
import numpy as np

def inversa_de_lista(matrices):
    inversas = []
    for i, M in enumerate(matrices):
        det = np.linalg.det(M)
        if det != 0:
            inv = np.linalg.inv(M)
            inversas.append(inv)
            print(f"Matriz {i+1} es no singular y su inversa es:\n{inv}\n")
        else:
            inversas.append(None)
            print(f"Matriz {i+1} es singular y no tiene inversa.\n")
    return inversas

def inversa(A):
    det = np.linalg.det(A)
    if det != 0:
        inv = np.linalg.inv(A)
        return inv
    else:
        print("La matriz proporcionada es singular y no tiene inversa.")
        return None

# Ejemplo de uso con una lista de matrices
matrices = [
    np.array([[4, 2, 6], [3, 0, 7], [-2, -1, -3]]),
    np.array([[1, 2, 0], [2, 1, -1], [3, 1, 1]]),
    np.array([[1, 1, -1, 1], [1, 2, -4, -2], [2, 1, 1, 5], [-1, 0, -2, -4]]),
    np.array([[4, 0, 0, 0], [6, 7, 0, 0], [9, 11, 1, 0], [5, 4, 1, 1]])
]

_ = inversa_de_lista(matrices)

# Ejemplo de uso con una única matriz
A = matrices[0]
inv_A = inversa(A)
if inv_A is not None:
    print(f"La inversa de la matriz A es:\n{inv_A}")


Matriz 1 es singular y no tiene inversa.

Matriz 2 es no singular y su inversa es:
[[-0.25   0.25   0.25 ]
 [ 0.625 -0.125 -0.125]
 [ 0.125 -0.625  0.375]]

Matriz 3 es singular y no tiene inversa.

Matriz 4 es no singular y su inversa es:
[[ 0.25        0.          0.          0.        ]
 [-0.21428571  0.14285714 -0.         -0.        ]
 [ 0.10714286 -1.57142857  1.         -0.        ]
 [-0.5         1.         -1.          1.        ]]

La matriz proporcionada es singular y no tiene inversa.


- Ejercicio 3

In [ ]:
import numpy as np

A = np.array([[1, -2, 2, -1], [1, 0, -1, 1], [2, 1, 3, -4], [0, -1, 1, -1]])
b1 = np.array([6, 4, -2, 5])
b2 = np.array([1, 1, 2, -1])

x1 = np.linalg.solve(A, b1)
x2 = np.linalg.solve(A, b2)

print("Solución del primer sistema:\n", x1)
print("\nSolución del segundo sistema:\n", x2)


Solución del primer sistema:
 [ 2.14285714 -6.85714286 -8.         -6.14285714]

Solución del segundo sistema:
 [1.14285714 1.14285714 2.         1.85714286]


- Ejercicio 4

In [ ]:
import sympy as sp

alpha = sp.symbols('alpha')

A = sp.Matrix([
    [1, -1, alpha],
    [2, 2, 1],
    [0, alpha, -3/2]
])

det_A = A.det()

singular_values = sp.solve(det_A, alpha)

print("Valores de α que hacen la matriz singular:", singular_values)

Valores de α que hacen la matriz singular: [-1.50000000000000, 2.00000000000000]


- Ejercicio 5

In [ ]:
import numpy as np

# Función para realizar la descomposición LU
def lu_decomposition(A):
    n = A.shape[0]
    L = np.eye(n)
    U = A.copy()

    for i in range(n):
        for j in range(i+1, n):
            L[j, i] = U[j, i] / U[i, i]
            U[j] = U[j] - L[j, i] * U[i]

    return L, U

def forward_substitution(L, b):
    n = L.shape[0]
    y = np.zeros(n)

    for i in range(n):
        y[i] = b[i] - np.dot(L[i, :i], y[:i])

    return y

def backward_substitution(U, y):
    n = U.shape[0]
    x = np.zeros(n)

    for i in range(n-1, -1, -1):
        x[i] = (y[i] - np.dot(U[i, i+1:], x[i+1:])) / U[i, i]

    return x

def solve_lu(A, b):
    L, U = lu_decomposition(A)
    y = forward_substitution(L, b)
    x = backward_substitution(U, y)
    return x

A_list = [
    np.array([[1, 0, 0], [2, 1, 0], [-1, 0, 1]], dtype=float),
    np.array([[2, 0, 0], [-1, 1, 0], [3, 2, -1]], dtype=float)
]

B_list = [
    np.array([[2, 3, -1], [0, -2, 1], [0, 0, 3]], dtype=float),
    np.array([[1, 1, 1], [0, 1, 2], [0, 0, 1]], dtype=float)
]

b_list = [
    np.array([2, -1, 1], dtype=float),
    np.array([-1, 3, 0], dtype=float)
]

A_combined = [A @ B for A, B in zip(A_list, B_list)]

solutions = [solve_lu(A, b) for A, b in zip(A_combined, b_list)]

for i, solution in enumerate(solutions):
    print(f"Solución del sistema {chr(97+i)}: {solution}")

Solución del sistema a: [-3.  3.  1.]
Solución del sistema b: [ 0.5 -4.5  3.5]


- Ejercicio 6

In [ ]:
from scipy.linalg import lu

# Definir matrices
matrices = [
    np.array([[2, -1, 1], [3, 3, 9], [3, 3, 5]]),
    np.array([[1.012, -2.132, 3.104], [-2.132, 4.096, -7.013], [3.104, -7.013, 0.014]]),
    np.array([[2, 0, 0, 0], [1, 1.5, 0, 0], [0, -3, 0.5, 0], [2, -2, 1, 1]]),
    np.array([[2.1756, 4.0231, -2.1732, 5.1967], [-4.0231, 6.0000, 0, 1.1973], [-1.0000, -5.2107, 1.1111, 0], [6.0235, 7.0000, 0, -4.1561]])
]

# Factorización LU
for i, M in enumerate(matrices):
    P, L, U = lu(M)
    print(f"\nMatriz {i+1}:")
    print("\nL:\n", L)
    print("\nU:\n", U)


Matriz 1:

L:
 [[ 1.          0.          0.        ]
 [ 0.66666667  1.          0.        ]
 [ 1.         -0.          1.        ]]

U:
 [[ 3.  3.  9.]
 [ 0. -3. -5.]
 [ 0.  0. -4.]]

Matriz 2:

L:
 [[ 1.          0.          0.        ]
 [-0.68685567  1.          0.        ]
 [ 0.32603093 -0.21424728  1.        ]]

U:
 [[ 3.104      -7.013       0.014     ]
 [ 0.         -0.72091881 -7.00338402]
 [ 0.          0.          1.59897957]]

Matriz 3:

L:
 [[ 1.          0.          0.          0.        ]
 [ 0.          1.          0.          0.        ]
 [ 1.          0.66666667  1.          0.        ]
 [ 0.5        -0.5         0.375       1.        ]]

U:
 [[ 2.          0.          0.          0.        ]
 [ 0.         -3.          0.5         0.        ]
 [ 0.          0.          0.66666667  1.        ]
 [ 0.          0.          0.         -0.375     ]]

Matriz 4:

L:
 [[ 1.          0.          0.          0.        ]
 [-0.66790072  1.          0.          0.        ]
 [ 0.3611

- Ejercicio 7

In [ ]:
import numpy as np

def lu_decomposition(A):
    n = A.shape[0]
    L = np.eye(n)
    U = A.copy()

    for i in range(n):
        for j in range(i+1, n):
            L[j, i] = U[j, i] / U[i, i]
            U[j] = U[j] - L[j, i] * U[i]

    return L, U

def forward_substitution(L, b):
    n = L.shape[0]
    y = np.zeros(n)

    for i in range(n):
        y[i] = b[i] - np.dot(L[i, :i], y[:i])

    return y

def backward_substitution(U, y):
    n = U.shape[0]
    x = np.zeros(n)

    for i in range(n-1, -1, -1):
        x[i] = (y[i] - np.dot(U[i, i+1:], x[i+1:])) / U[i, i]

    return x

def solve_lu(A, b):
    L, U = lu_decomposition(A)
    y = forward_substitution(L, b)
    x = backward_substitution(U, y)
    return x

A_list = [
    np.array([[2, -1, 1], [3, 3, 9], [3, 3, 5]], dtype=float),
    np.array([[1.012, -2.132, 3.104], [-2.132, 4.096, -7.013], [3.104, -7.013, 0.014]], dtype=float),
    np.array([[2, 0, 0, 0], [1, 1.5, 0, 0], [0, -3, 0.5, 0], [2, -2, 1, 1]], dtype=float),
    np.array([[2.1756, 4.0231, -2.1732, 5.1967], [-4.0231, 6.0000, 0, 1.1973], [-1.0000, -5.2107, 1.1111, 0], [6.0235, 7.0000, 0, -4.1561]], dtype=float)
]

b_list = [
    np.array([-1, 0, 4], dtype=float),
    np.array([1.984, -5.049, -3.895], dtype=float),
    np.array([3, 4.5, -6.6, 0.8], dtype=float),
    np.array([17.102, -6.1593, 3.0004, 0], dtype=float)
]

solutions = [solve_lu(A, b) for A, b in zip(A_list, b_list)]

for i, solution in enumerate(solutions):
    print(f"Solución del sistema {chr(97+i)}: {solution}")

Solución del sistema a: [ 1.  2. -1.]
Solución del sistema b: [1. 1. 1.]
Solución del sistema c: [ 1.5  2.  -1.2  3. ]
Solución del sistema d: [2.9398512  0.0706777  5.67773512 4.37981223]
